// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAiIIy6SM6W2Oer4RPjv6Lxx52tGbw7OU',
    appId: '1:221344695094:web:67c1f3737a9062fbc7e997',
    messagingSenderId: '221344695094',
    projectId: 'tailorconnect-b25b5',
    authDomain: 'tailorconnect-b25b5.firebaseapp.com',
    storageBucket: 'tailorconnect-b25b5.firebasestorage.app',
    measurementId: 'G-TV650542L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzqK20r2anWvr2FQIoQAxxo4ZRl7U8LcI',
    appId: '1:221344695094:android:a441b83c06f4ec35c7e997',
    messagingSenderId: '221344695094',
    projectId: 'tailorconnect-b25b5',
    storageBucket: 'tailorconnect-b25b5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAiIIy6SM6W2Oer4RPjv6Lxx52tGbw7OU',
    appId: '1:221344695094:web:bd0f6914b8ea03f2c7e997',
    messagingSenderId: '221344695094',
    projectId: 'tailorconnect-b25b5',
    authDomain: 'tailorconnect-b25b5.firebaseapp.com',
    storageBucket: 'tailorconnect-b25b5.firebasestorage.app',
    measurementId: 'G-JLX3PTLVK5',
  );
}
